name: Install dependencies
description: Install node, pnpm, and dependencies

inputs:
  node-version:
    description: "Node.js version"
    default: "24"
  pnpm-version:
    description: "pnpm version (optional)"
    required: false
  cwd:
    description: "Working directory for pnpm commands"
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ inputs.node-version }}

    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      name: Install pnpm
      id: pnpm-install
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Audit dependencies for critical vulnerabilities
      shell: bash
      working-directory: ${{ inputs.cwd }}
      run: pnpm audit --audit-level=critical --ignore-registry-errors

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.cwd }}
      run: pnpm install
